## Numpy

**NumPy (Numerical Python)** is a powerful library for numerical and scientific computing in Python. It provides support for multi-dimensional arrays and matrices, along with performing mathematical operations efficiently.

In Python we have lists that serve the same purpose as arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. While Python lists are flexible, they are slow for numerical computations. NumPy arrays are faster, Memory Efficient, Convenient, support vectorization, etc.

The array object in NumPy is called ndarray. Arrays are very frequently used in the AI field, where speed and resources are very important.

In [1]:
# Import library
import numpy as np

### Numpy arrays


* 0D Array (Scalar) - this holds a single value

In [3]:
arr = np.array(3)

print(arr)
print(type(arr))
print(arr.shape)

3
<class 'numpy.ndarray'>
()


* 1D Array(Vector) - 
This is a simple, linear list of elements, all of the same data type, stored sequentially in a single row.

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)
print(arr1.shape) # From the output ther is just 5 columns

[1 2 3 4 5]
(5,)


* 2D Array(Matrix) - Stores data in a table like format

In [6]:
arr2 = np.array([[1, 2], [3, 4], [5, 6]])

print(arr2)
print(arr2.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


* 3D Array(Tensor) - Similar to stacking multiple tables on top of each other

In [7]:
arr3 = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8]],
    [[0, 1, 2, 3], [4, 5, 6, 7]],
    [[9, 8, 7, 6], [2, 3, 5, 6]]
])

print(arr3)

print(arr3.shape)

[[[1 2 3 4]
  [5 6 7 8]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[9 8 7 6]
  [2 3 5 6]]]
(3, 2, 4)


* Built in Array functions

In [8]:
zeros = np.zeros((4, 5)) # This is a 2D(4*5) array of zeros

print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
ones = np.ones((2, 4, 2))

print(ones)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [10]:
# using .full() to populate with other values
fives = np.full((2, 3, 2), 5)

print(fives)

[[[5 5]
  [5 5]
  [5 5]]

 [[5 5]
  [5 5]
  [5 5]]]


In [11]:
# using .eye() to create an identity matrix
id_matrix = np.eye(3) # 3 * 3 identity matrix
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# using .random.rand() to create a random float array
random_arr = np.random.rand(3, 4)

print(random_arr)

[[0.81604232 0.51026173 0.72711056 0.22716043]
 [0.59582376 0.14569278 0.70899695 0.56098096]
 [0.81289438 0.88956752 0.97742231 0.87465642]]


In [13]:
# .random.randint() for random integers

random_arr1 = np.random.randint(1, 10, (4, 4)) # 4*4 with random integers ranging from 0 -9

print(random_arr1)

[[1 9 4 4]
 [3 6 9 1]
 [9 9 4 8]
 [2 5 9 4]]


* Checking the Properties or Attributes of an Array

In [14]:
print(random_arr)

[[0.81604232 0.51026173 0.72711056 0.22716043]
 [0.59582376 0.14569278 0.70899695 0.56098096]
 [0.81289438 0.88956752 0.97742231 0.87465642]]


In [16]:
# Shape of an array
print(random_arr.shape)

(3, 4)


In [17]:
# Dimension of an array
print(random_arr.ndim)

2


In [18]:
# Total number of elements in an array
print(random_arr.size)

12


In [19]:
# Data types present
print(random_arr.dtype)

float64


#### Accessing Elements in Arrays

* Indexing

In [24]:
# First element in a 3D array
print(random_arr[0, 0])

# First row in a 3D array
print(random_arr[0])

# First element in a 1D array
print(arr1[0])

0.8160423157818831
[0.81604232 0.51026173 0.72711056 0.22716043]
1


* Slicing

In [25]:
print(arr1)
print(arr1[:2])

[1 2 3 4 5]
[1 2]


#### Modifying Elements

In [26]:
# Let's do some arithmetic operations on two arrays and see the output
arr_mod1 = np.array([2, 4, 6])
arr_mod2 = np.array([8, 10, 12])

# Let's add
print(f"add_result: {arr_mod1 + arr_mod2}")
print()

# Let's multiply
print(f"multiply_result: {arr_mod1 * arr_mod2}")
print()

# Let's divide
print(f"divide_result: {arr_mod1 / arr_mod2}")

add_result: [10 14 18]

multiply_result: [16 40 72]

divide_result: [0.25 0.4  0.5 ]


In [27]:
# Let's modify an element in "arr_mod1"
arr_mod1[2] = 8
print(f"modified_arr: {arr_mod1}")

modified_arr: [2 4 8]


#### Reshaping Arrays

In [28]:
# Define an array
arr_def = np.array([1, 2, 3, 4, 5, 6,])

# Lets reshape to a 2 by 3 array using .reshape()
reshaped_arr = arr_def.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [29]:
# It is also possible to flatten multi-dimensional arrays to 1 dimension.
flattened_arr = reshaped_arr.flatten()

print(flattened_arr)
print(flattened_arr.shape)

[1 2 3 4 5 6]
(6,)


#### Aggregation and Statistical Operatons

In [30]:
# Define an array
arr_new = np.array([1, 2, 3, 4, 5])

In [31]:
# Let's sum all the elements in the array
print(np.sum(arr_new))

15


In [32]:
# Let's take the mean of the array
print(np.mean(arr_new))

3.0


In [33]:
# Let's check the median number in the array
print(np.median(arr_new))

3.0


In [34]:
# We can also check the standard deviation
print(np.std(arr_new))

1.4142135623730951


#### Random stuffs


In [37]:
main_arr = np.random.randint(1, 100, (3, 4))

print(main_arr)

[[66 67 95 29]
 [37 53 20 30]
 [80 94 33 31]]


In [38]:
# First 2 rows
print(main_arr[:2])

[[66 67 95 29]
 [37 53 20 30]]


In [40]:
# Last 3 columns
print(main_arr[:, -3:]) # first : selects all rows, the second ':' the last 3 columns

[[67 95 29]
 [53 20 30]
 [94 33 31]]


In [42]:
# Get all even numbers in the array
print(main_arr[main_arr % 2 == 0]) # the [] contains the constraint

[66 20 30 80 94]


In [43]:
# Convert to 3D array (2 * 2 * 3)
new_main = main_arr.reshape(2, 2, 3)

print(new_main)

[[[66 67 95]
  [29 37 53]]

 [[20 30 80]
  [94 33 31]]]


In [45]:
# Flatten to 1D
new_main1 = new_main.flatten()

print(new_main1)

[66 67 95 29 37 53 20 30 80 94 33 31]


In [46]:
# Generate a 4x4 identity matrix
id_mat = np.eye(4)

print(id_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [51]:
# Replace 1 with random numbers
np.fill_diagonal(id_mat, np.arange(10, 50, 10))

print(id_mat)

[[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


In [52]:
# Random 3*4 and 4*3 matrices
arr34 = np.random.randint(1, 10, (3, 4))
arr43 = np.random.randint(1, 10, (4, 3))

print(arr34)
print(arr43)

[[6 7 9 9]
 [6 1 5 3]
 [3 7 2 5]]
[[1 5 8]
 [2 1 3]
 [2 8 7]
 [2 5 8]]


In [55]:
# Matrix multiplication
print(arr34 @ arr43)

[[ 56 154 204]
 [ 24  86 110]
 [ 31  63  99]]


In [57]:
# Function receives a 2D array as input and then returns a new array
# where all even numbers are squared and all odd numbers are replaced with -1
def array_mod(arr):
    return np.where(arr % 2 == 0, arr ** 2, -1)

In [58]:
trial_matrix = np.random.randint(1, 10, (3, 3))

print(trial_matrix)

[[3 9 5]
 [3 2 4]
 [7 5 4]]


In [59]:
mod_matrix = array_mod(trial_matrix)
print(mod_matrix)

[[-1 -1 -1]
 [-1  4 16]
 [-1 -1 16]]
